project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"

website:
  title: "30 Day Map Challenge"
  navbar: false
  back-to-top-navigation: true
  site-url: "https://guillaume-noblet/30DayMapChallenge"
  repo-url: "https://github.com/gnoblet/30DayMapChallenge"
  favicon: "images/favicon.png"
  page-navigation: true

format:
  html:
    theme: [cosmo, styles.scss]
    mainfont: "Inter"
    toc: false
    highlight-style: github
    smooth-scroll: true
    title-block-banner: false
    grid:
      sidebar-width: 250px
      body-width: 700px
      margin-width: 200px

execute:
  freeze: auto
  warning: false
  message: false
  
resources: 
  - fonts/
